// PLACEHOLDER — regenerated by `npm run gen:types` once tables exist (WS1+).
// Keeping a minimal shape here lets the typed clients compile on the empty app.
// Do not hand-edit beyond this placeholder; the generator overwrites it.
export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
